// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh3yZRLCdV-DHL18VJyU2gRVVwiqWD088',
    appId: '1:747279423715:web:9547ebc8f2c29824370dd6',
    messagingSenderId: '747279423715',
    projectId: 'sports-app-717fd',
    authDomain: 'sports-app-717fd.firebaseapp.com',
    storageBucket: 'sports-app-717fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqB0bOaRMUtmYi_8fZO5i8j4M0q5cRIg',
    appId: '1:747279423715:android:959c8c53157759db370dd6',
    messagingSenderId: '747279423715',
    projectId: 'sports-app-717fd',
    storageBucket: 'sports-app-717fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtuTyM4ffFqxsKbYDHh85fJdLle51xI4',
    appId: '1:747279423715:ios:0aa5a8a69aa47c40370dd6',
    messagingSenderId: '747279423715',
    projectId: 'sports-app-717fd',
    storageBucket: 'sports-app-717fd.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

}